---
name: NetSDS-Queue
version: 0.01
author:
  - 'Net.Style Development Team <info@netstyle.com.ua>'
abstract: Perl5 modules for NetSDS messaging queue
license: gpl
resources:
  license: http://opensource.org/licenses/gpl-license.php
requires:
  JSON: 2.0
  JSON::XS: 0
  NetSDS: 1.02
  perl: 5.008
  version: 0
build_requires:
  Module::Build: 0
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
provides:
  NetSDS::Queue:
    file: lib/NetSDS/Queue.pm
    version: 0.01
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
